export const sampleAlignment = `CLUSTAL W (1.83) multiple sequence alignment

Kinase_A      MSEQQRITLKELNHPNIVKLLDVANMGTN---KLELPEVAKAAEEAGVEVVV
Kinase_B      MTEQQRITLKELNHPNIVKLLDIANMGTN---KLELPEVAKAAEEAGVEVVI
Kinase_C      MPEQQRITLKELNHPNIVKLLDVANMGSN---KLELPEVAKAAEEAGIEVVI
Kinase_D      MSEQQRITLKELNHPNIVKLLDVANMGTNQAAKLELPEVAKAAEEAGVEVVI
             *.***********************.   *******************:*

Kinase_A      DLKSTGKVVAIKKLNNQNVVAMNQLEKHGADVVAVTPEEAKKAGVEVVVTDT
Kinase_B      DLKSTGKVVAIKKLNNQNVVAMNQLEKHGADVVAVTPEEAKKAGVEVVVTDT
Kinase_C      DLKSTGKVVAIKKLNNQNVVAMNQLEKHGADIVAVTPEEAKKAGVEVVVTDT
Kinase_D      DLKSTGKVVAIKKLNNQNVVAMNQLEKHGADVVAVTPEEAKKAGVEVVVTDT
             ******************************:********************

Kinase_A      GQEVLAVVKANEEGADVVVVDDERKALNQLGITPEE
Kinase_B      GQEVLAVVKANEEGADVVVVDDERKALNQLGITPEE
Kinase_C      GQEVLAVVKANEEGADVVVVDDERKALNQLGITPEE
Kinase_D      GQEVLAVVKANEEGADVVVVDDERKALNQLGITPEE
             ****************************************`;
